repos:
  # Встроенные хуки pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace        # Удаляет пробелы в конце строк
      - id: end-of-file-fixer         # Добавляет пустую строку в конец файла
      - id: check-yaml                # Проверяет синтаксис YAML файлов
      - id: check-toml                # Проверяет синтаксис TOML файлов
      - id: check-json                # Проверяет синтаксис JSON файлов
      - id: check-added-large-files   # Предотвращает добавление больших файлов
      - id: check-merge-conflict      # Проверяет на конфликты слияния
      - id: debug-statements          # Проверяет на отладочные print/pdb

  # Black - форматирование кода
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.13

  # isort - сортировка импортов
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # mypy - проверка типов
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503
