version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/pg_data
